# Aliases
alias be='bundle exec'
alias c='clear'
alias chrome='open -a google\ chrome'
alias chromium='open -a chromium'
alias copyLastCmd='fc -ln -1 | awk '\''{$1=$1}1'\'' ORS='\'''\'' | pbcopy'
alias f='open -a Finder '
alias fh='open -a Finder .'
alias filemerge='open -a '\''/Developer/Applications/Utilities/FileMerge.app'\'''
alias firefox='open -a firefox'
alias flush='dscacheutil -flushcache'
alias g='git'
alias gcur='git current'
alias gc='git commit -v'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git commit -v -m'
alias gp='git push'
alias gpo='git push origin'
alias gpu='git push -u origin $(g current)'
alias grbme='git checkout master && git pull && git checkout - && git rebase master'
alias ls='ls -A'
alias ll='ls -Al'
alias piano='pianobar'
alias ql='qlmanage -p 2>/dev/null'
alias rd='rmdir'
alias safari='open -a safari'
alias trl="taskrunner --list | fzf | xargs taskrunner"
