#!bin/sh

if [ uname == "Darwin" ]; then
  echo "/n Installing XCode Dev Tools..."
  xcode-select --install

  echo "/n Installing HomeBrew..."
  if [ command -v brew >/dev/null 2>&1 ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "/n Installing from HomeBrew bundle..."
  brew bundle
fi

